jira:
  image: centular/docker-atlassian-jira-software
  restart: always
  links:
    - mysql-jira:mysql
  ports:
    - 8888:8080
  volumes:
    - /opt/jira/jira:/var/atlassian/jira

mysql-jira:
  image: mysql:latest
  volumes:
    - /opt/jira/mysql:/var/lib/mysql
  restart: always
  environment:
    - MYSQL_ROOT_PASSWORD=jira
    - MYSQL_DATABASE=jira
    - MYSQL_USER=jira
    - MYSQL_PASSWORD=jira